version: "2.0"
services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=repdb